# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from v1 import broker_pb2 as v1_dot_broker__pb2


class BrokerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/broker.v1.Broker/Health',
                request_serializer=v1_dot_broker__pb2.HealthRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListManagedAccounts = channel.unary_unary(
                '/broker.v1.Broker/ListManagedAccounts',
                request_serializer=v1_dot_broker__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.AccountsResponse.FromString,
                _registered_method=True)
        self.GetAccountSummary = channel.unary_unary(
                '/broker.v1.Broker/GetAccountSummary',
                request_serializer=v1_dot_broker__pb2.AccountRef.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.SummaryResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/broker.v1.Broker/GetPositions',
                request_serializer=v1_dot_broker__pb2.AccountRef.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.PositionsResponse.FromString,
                _registered_method=True)
        self.GetOrders = channel.unary_unary(
                '/broker.v1.Broker/GetOrders',
                request_serializer=v1_dot_broker__pb2.AccountRef.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.OrdersResponse.FromString,
                _registered_method=True)
        self.GetContract = channel.unary_unary(
                '/broker.v1.Broker/GetContract',
                request_serializer=v1_dot_broker__pb2.ContractRef.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.ContractResponse.FromString,
                _registered_method=True)
        self.PlaceOrder = channel.unary_unary(
                '/broker.v1.Broker/PlaceOrder',
                request_serializer=v1_dot_broker__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.PlaceOrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/broker.v1.Broker/CancelOrder',
                request_serializer=v1_dot_broker__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.OrderEvent = channel.unary_stream(
                '/broker.v1.Broker/OrderEvent',
                request_serializer=v1_dot_broker__pb2.AccountRef.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.OrderEventMessage.FromString,
                _registered_method=True)
        self.SearchContracts = channel.unary_unary(
                '/broker.v1.Broker/SearchContracts',
                request_serializer=v1_dot_broker__pb2.SearchContractsRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.SearchContractsResponse.FromString,
                _registered_method=True)
        self.ModifyOrder = channel.unary_unary(
                '/broker.v1.Broker/ModifyOrder',
                request_serializer=v1_dot_broker__pb2.ModifyOrderRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.ModifyOrderResponse.FromString,
                _registered_method=True)
        self.PlaceBracket = channel.unary_unary(
                '/broker.v1.Broker/PlaceBracket',
                request_serializer=v1_dot_broker__pb2.PlaceBracketRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.PlaceBracketResponse.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/broker.v1.Broker/Configure',
                request_serializer=v1_dot_broker__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.StreamQuotes = channel.stream_stream(
                '/broker.v1.Broker/StreamQuotes',
                request_serializer=v1_dot_broker__pb2.StreamQuotesRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.QuoteMessage.FromString,
                _registered_method=True)
        self.GetHistoricalBars = channel.unary_unary(
                '/broker.v1.Broker/GetHistoricalBars',
                request_serializer=v1_dot_broker__pb2.GetHistoricalBarsRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.GetHistoricalBarsResponse.FromString,
                _registered_method=True)
        self.PreviewOrder = channel.unary_unary(
                '/broker.v1.Broker/PreviewOrder',
                request_serializer=v1_dot_broker__pb2.PreviewOrderRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.PreviewOrderResponse.FromString,
                _registered_method=True)
        self.GetOptionChain = channel.unary_unary(
                '/broker.v1.Broker/GetOptionChain',
                request_serializer=v1_dot_broker__pb2.OptionChainRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.OptionChainResponse.FromString,
                _registered_method=True)
        self.GetOptionExpirations = channel.unary_unary(
                '/broker.v1.Broker/GetOptionExpirations',
                request_serializer=v1_dot_broker__pb2.OptionExpirationsRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.OptionExpirationsResponse.FromString,
                _registered_method=True)
        self.StreamOptionGreeks = channel.unary_stream(
                '/broker.v1.Broker/StreamOptionGreeks',
                request_serializer=v1_dot_broker__pb2.OptionGreeksRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.OptionGreeksResponse.FromString,
                _registered_method=True)
        self.ExerciseOption = channel.unary_unary(
                '/broker.v1.Broker/ExerciseOption',
                request_serializer=v1_dot_broker__pb2.ExerciseOptionRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.ExerciseOptionResponse.FromString,
                _registered_method=True)
        self.PlaceCombo = channel.unary_unary(
                '/broker.v1.Broker/PlaceCombo',
                request_serializer=v1_dot_broker__pb2.PlaceComboRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.PlaceComboResponse.FromString,
                _registered_method=True)
        self.GetSupportedComboStrategies = channel.unary_unary(
                '/broker.v1.Broker/GetSupportedComboStrategies',
                request_serializer=v1_dot_broker__pb2.GetSupportedComboStrategiesRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.GetSupportedComboStrategiesResponse.FromString,
                _registered_method=True)
        self.GetFutureContracts = channel.unary_unary(
                '/broker.v1.Broker/GetFutureContracts',
                request_serializer=v1_dot_broker__pb2.GetFutureContractsRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.GetFutureContractsResponse.FromString,
                _registered_method=True)
        self.StreamSettlementEvents = channel.unary_stream(
                '/broker.v1.Broker/StreamSettlementEvents',
                request_serializer=v1_dot_broker__pb2.StreamSettlementEventsRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.SettlementEvent.FromString,
                _registered_method=True)
        self.RequestFxQuote = channel.unary_unary(
                '/broker.v1.Broker/RequestFxQuote',
                request_serializer=v1_dot_broker__pb2.FxQuoteRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.FxQuoteResponse.FromString,
                _registered_method=True)
        self.AcceptFxQuote = channel.unary_unary(
                '/broker.v1.Broker/AcceptFxQuote',
                request_serializer=v1_dot_broker__pb2.FxAcceptRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.FxAcceptResponse.FromString,
                _registered_method=True)
        self.CancelFxQuote = channel.unary_unary(
                '/broker.v1.Broker/CancelFxQuote',
                request_serializer=v1_dot_broker__pb2.FxCancelRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.StreamFxRates = channel.unary_stream(
                '/broker.v1.Broker/StreamFxRates',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.FxMidRate.FromString,
                _registered_method=True)


class BrokerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListManagedAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchContracts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceBracket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Phase 6: backend ships per-sidecar credentials (futu unlock + RSA priv)
        at registry boot. IBKR sidecars implement as no-op-returning-ok.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamQuotes(self, request_iterator, context):
        """Phase 7b.1 — bidirectional streaming quotes. Backend dials sidecar
        (sidecar = gRPC server, matches Health/GetPositions). Subscribe/Unsubscribe/
        Resync/Heartbeat travel client→server; QuoteMessage travels server→client.
        See spec docs/superpowers/specs/2026-05-04-phase7b1-streaming-quotes-design.md §4.2.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalBars(self, request, context):
        """Phase 9 — historical OHLCV backfill. BarService calls this for cache misses
        and pre-warm; sidecar chunks/paces internally per broker SDK quotas.
        See docs/superpowers/specs/2026-05-07-phase9-charting-design.md §4 lines 622-645.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewOrder(self, request, context):
        """Phase 10a — pre-trade margin/risk preview RPC. IBKR uses ib_async
        placeOrder(whatIf=True) + filledEvent.wait; Schwab uses POST
        /trader/v1/accounts/{accountHash}/previewOrder; Alpaca returns
        UNIMPLEMENTED. Money fields are Decimal-strings per [C2].
        Spec: docs/superpowers/specs/2026-05-08-phase10a-risk-engine-design.md §5.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOptionChain(self, request, context):
        """── Phase 12: Options ───────────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOptionExpirations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamOptionGreeks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExerciseOption(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceCombo(self, request, context):
        """Phase 13: Multi-leg option combos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportedComboStrategies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFutureContracts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSettlementEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestFxQuote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptFxQuote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelFxQuote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFxRates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=v1_dot_broker__pb2.HealthRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.HealthResponse.SerializeToString,
            ),
            'ListManagedAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListManagedAccounts,
                    request_deserializer=v1_dot_broker__pb2.Empty.FromString,
                    response_serializer=v1_dot_broker__pb2.AccountsResponse.SerializeToString,
            ),
            'GetAccountSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountSummary,
                    request_deserializer=v1_dot_broker__pb2.AccountRef.FromString,
                    response_serializer=v1_dot_broker__pb2.SummaryResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=v1_dot_broker__pb2.AccountRef.FromString,
                    response_serializer=v1_dot_broker__pb2.PositionsResponse.SerializeToString,
            ),
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=v1_dot_broker__pb2.AccountRef.FromString,
                    response_serializer=v1_dot_broker__pb2.OrdersResponse.SerializeToString,
            ),
            'GetContract': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContract,
                    request_deserializer=v1_dot_broker__pb2.ContractRef.FromString,
                    response_serializer=v1_dot_broker__pb2.ContractResponse.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=v1_dot_broker__pb2.PlaceOrderRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.PlaceOrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=v1_dot_broker__pb2.CancelOrderRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.CancelOrderResponse.SerializeToString,
            ),
            'OrderEvent': grpc.unary_stream_rpc_method_handler(
                    servicer.OrderEvent,
                    request_deserializer=v1_dot_broker__pb2.AccountRef.FromString,
                    response_serializer=v1_dot_broker__pb2.OrderEventMessage.SerializeToString,
            ),
            'SearchContracts': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchContracts,
                    request_deserializer=v1_dot_broker__pb2.SearchContractsRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.SearchContractsResponse.SerializeToString,
            ),
            'ModifyOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyOrder,
                    request_deserializer=v1_dot_broker__pb2.ModifyOrderRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.ModifyOrderResponse.SerializeToString,
            ),
            'PlaceBracket': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBracket,
                    request_deserializer=v1_dot_broker__pb2.PlaceBracketRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.PlaceBracketResponse.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=v1_dot_broker__pb2.ConfigureRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.ConfigureResponse.SerializeToString,
            ),
            'StreamQuotes': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamQuotes,
                    request_deserializer=v1_dot_broker__pb2.StreamQuotesRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.QuoteMessage.SerializeToString,
            ),
            'GetHistoricalBars': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoricalBars,
                    request_deserializer=v1_dot_broker__pb2.GetHistoricalBarsRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.GetHistoricalBarsResponse.SerializeToString,
            ),
            'PreviewOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewOrder,
                    request_deserializer=v1_dot_broker__pb2.PreviewOrderRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.PreviewOrderResponse.SerializeToString,
            ),
            'GetOptionChain': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOptionChain,
                    request_deserializer=v1_dot_broker__pb2.OptionChainRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.OptionChainResponse.SerializeToString,
            ),
            'GetOptionExpirations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOptionExpirations,
                    request_deserializer=v1_dot_broker__pb2.OptionExpirationsRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.OptionExpirationsResponse.SerializeToString,
            ),
            'StreamOptionGreeks': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamOptionGreeks,
                    request_deserializer=v1_dot_broker__pb2.OptionGreeksRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.OptionGreeksResponse.SerializeToString,
            ),
            'ExerciseOption': grpc.unary_unary_rpc_method_handler(
                    servicer.ExerciseOption,
                    request_deserializer=v1_dot_broker__pb2.ExerciseOptionRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.ExerciseOptionResponse.SerializeToString,
            ),
            'PlaceCombo': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceCombo,
                    request_deserializer=v1_dot_broker__pb2.PlaceComboRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.PlaceComboResponse.SerializeToString,
            ),
            'GetSupportedComboStrategies': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedComboStrategies,
                    request_deserializer=v1_dot_broker__pb2.GetSupportedComboStrategiesRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.GetSupportedComboStrategiesResponse.SerializeToString,
            ),
            'GetFutureContracts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFutureContracts,
                    request_deserializer=v1_dot_broker__pb2.GetFutureContractsRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.GetFutureContractsResponse.SerializeToString,
            ),
            'StreamSettlementEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSettlementEvents,
                    request_deserializer=v1_dot_broker__pb2.StreamSettlementEventsRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.SettlementEvent.SerializeToString,
            ),
            'RequestFxQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestFxQuote,
                    request_deserializer=v1_dot_broker__pb2.FxQuoteRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.FxQuoteResponse.SerializeToString,
            ),
            'AcceptFxQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptFxQuote,
                    request_deserializer=v1_dot_broker__pb2.FxAcceptRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.FxAcceptResponse.SerializeToString,
            ),
            'CancelFxQuote': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelFxQuote,
                    request_deserializer=v1_dot_broker__pb2.FxCancelRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'StreamFxRates': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFxRates,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_broker__pb2.FxMidRate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'broker.v1.Broker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('broker.v1.Broker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Broker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/Health',
            v1_dot_broker__pb2.HealthRequest.SerializeToString,
            v1_dot_broker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListManagedAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/ListManagedAccounts',
            v1_dot_broker__pb2.Empty.SerializeToString,
            v1_dot_broker__pb2.AccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetAccountSummary',
            v1_dot_broker__pb2.AccountRef.SerializeToString,
            v1_dot_broker__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetPositions',
            v1_dot_broker__pb2.AccountRef.SerializeToString,
            v1_dot_broker__pb2.PositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetOrders',
            v1_dot_broker__pb2.AccountRef.SerializeToString,
            v1_dot_broker__pb2.OrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetContract',
            v1_dot_broker__pb2.ContractRef.SerializeToString,
            v1_dot_broker__pb2.ContractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/PlaceOrder',
            v1_dot_broker__pb2.PlaceOrderRequest.SerializeToString,
            v1_dot_broker__pb2.PlaceOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/CancelOrder',
            v1_dot_broker__pb2.CancelOrderRequest.SerializeToString,
            v1_dot_broker__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OrderEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/broker.v1.Broker/OrderEvent',
            v1_dot_broker__pb2.AccountRef.SerializeToString,
            v1_dot_broker__pb2.OrderEventMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchContracts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/SearchContracts',
            v1_dot_broker__pb2.SearchContractsRequest.SerializeToString,
            v1_dot_broker__pb2.SearchContractsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/ModifyOrder',
            v1_dot_broker__pb2.ModifyOrderRequest.SerializeToString,
            v1_dot_broker__pb2.ModifyOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceBracket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/PlaceBracket',
            v1_dot_broker__pb2.PlaceBracketRequest.SerializeToString,
            v1_dot_broker__pb2.PlaceBracketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/Configure',
            v1_dot_broker__pb2.ConfigureRequest.SerializeToString,
            v1_dot_broker__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamQuotes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/broker.v1.Broker/StreamQuotes',
            v1_dot_broker__pb2.StreamQuotesRequest.SerializeToString,
            v1_dot_broker__pb2.QuoteMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoricalBars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetHistoricalBars',
            v1_dot_broker__pb2.GetHistoricalBarsRequest.SerializeToString,
            v1_dot_broker__pb2.GetHistoricalBarsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/PreviewOrder',
            v1_dot_broker__pb2.PreviewOrderRequest.SerializeToString,
            v1_dot_broker__pb2.PreviewOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOptionChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetOptionChain',
            v1_dot_broker__pb2.OptionChainRequest.SerializeToString,
            v1_dot_broker__pb2.OptionChainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOptionExpirations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetOptionExpirations',
            v1_dot_broker__pb2.OptionExpirationsRequest.SerializeToString,
            v1_dot_broker__pb2.OptionExpirationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamOptionGreeks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/broker.v1.Broker/StreamOptionGreeks',
            v1_dot_broker__pb2.OptionGreeksRequest.SerializeToString,
            v1_dot_broker__pb2.OptionGreeksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExerciseOption(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/ExerciseOption',
            v1_dot_broker__pb2.ExerciseOptionRequest.SerializeToString,
            v1_dot_broker__pb2.ExerciseOptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceCombo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/PlaceCombo',
            v1_dot_broker__pb2.PlaceComboRequest.SerializeToString,
            v1_dot_broker__pb2.PlaceComboResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportedComboStrategies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetSupportedComboStrategies',
            v1_dot_broker__pb2.GetSupportedComboStrategiesRequest.SerializeToString,
            v1_dot_broker__pb2.GetSupportedComboStrategiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFutureContracts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetFutureContracts',
            v1_dot_broker__pb2.GetFutureContractsRequest.SerializeToString,
            v1_dot_broker__pb2.GetFutureContractsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSettlementEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/broker.v1.Broker/StreamSettlementEvents',
            v1_dot_broker__pb2.StreamSettlementEventsRequest.SerializeToString,
            v1_dot_broker__pb2.SettlementEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestFxQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/RequestFxQuote',
            v1_dot_broker__pb2.FxQuoteRequest.SerializeToString,
            v1_dot_broker__pb2.FxQuoteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptFxQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/AcceptFxQuote',
            v1_dot_broker__pb2.FxAcceptRequest.SerializeToString,
            v1_dot_broker__pb2.FxAcceptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelFxQuote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/CancelFxQuote',
            v1_dot_broker__pb2.FxCancelRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFxRates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/broker.v1.Broker/StreamFxRates',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_broker__pb2.FxMidRate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BackendCallbackStub(object):
    """Phase 7a — sidecar→backend single-writer token-refresh callback (architect C2).
    This service is implemented by the BACKEND (not by sidecars). Sidecars are
    gRPC clients of this service when they need a fresh token pair. Backend
    holds the PG advisory lock during the actual refresh; sidecars never call
    Schwab's /oauth/token endpoint directly.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestTokenRefresh = channel.unary_unary(
                '/broker.v1.BackendCallback/RequestTokenRefresh',
                request_serializer=v1_dot_broker__pb2.TokenRefreshRequest.SerializeToString,
                response_deserializer=v1_dot_broker__pb2.TokenRefreshResponse.FromString,
                _registered_method=True)


class BackendCallbackServicer(object):
    """Phase 7a — sidecar→backend single-writer token-refresh callback (architect C2).
    This service is implemented by the BACKEND (not by sidecars). Sidecars are
    gRPC clients of this service when they need a fresh token pair. Backend
    holds the PG advisory lock during the actual refresh; sidecars never call
    Schwab's /oauth/token endpoint directly.
    """

    def RequestTokenRefresh(self, request, context):
        """broker_id selects which broker's tokens to refresh. Only "schwab"
        currently uses this path; other brokers reuse their existing auth.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackendCallbackServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestTokenRefresh': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTokenRefresh,
                    request_deserializer=v1_dot_broker__pb2.TokenRefreshRequest.FromString,
                    response_serializer=v1_dot_broker__pb2.TokenRefreshResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'broker.v1.BackendCallback', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('broker.v1.BackendCallback', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BackendCallback(object):
    """Phase 7a — sidecar→backend single-writer token-refresh callback (architect C2).
    This service is implemented by the BACKEND (not by sidecars). Sidecars are
    gRPC clients of this service when they need a fresh token pair. Backend
    holds the PG advisory lock during the actual refresh; sidecars never call
    Schwab's /oauth/token endpoint directly.
    """

    @staticmethod
    def RequestTokenRefresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.BackendCallback/RequestTokenRefresh',
            v1_dot_broker__pb2.TokenRefreshRequest.SerializeToString,
            v1_dot_broker__pb2.TokenRefreshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
