/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Account Alias */
        patch: operations["update_account_alias_api_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/accounts/{account_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Orders */
        get: operations["get_account_orders_api_accounts__account_id__orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Positions */
        get: operations["get_account_positions_api_accounts__account_id__positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Summary */
        get: operations["get_account_summary_api_accounts__account_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brokers/schwab/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disconnect Schwab
         * @description Phase 7a D4 — wipe Schwab tokens (always); optionally wipe Tier-2 creds.
         */
        post: operations["disconnect_schwab_api_admin_brokers_schwab_disconnect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brokers/schwab/oauth-callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schwab Oauth Callback Admin */
        post: operations["schwab_oauth_callback_admin_api_admin_brokers_schwab_oauth_callback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brokers/schwab/oauth-start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schwab Oauth Start */
        get: operations["schwab_oauth_start_api_admin_brokers_schwab_oauth_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brokers/schwab/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Schwab Status */
        get: operations["schwab_status_api_admin_brokers_schwab_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brokers/{label}/account-hashes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Broker Account Hashes
         * @description Operator-only: returns sidecar-side (account_number, account_hash, mode)
         *     for a broker gateway label.
         *
         *     Used to discover SCHWAB_PAPER_ACCOUNT_HASH for the C0 empirical hard-gate
         *     script (and equivalent operator workflows for other brokers). Bypasses the
         *     boundary-stripping in AccountResponse / _account_from_proto by reading
         *     response.accounts directly from the sidecar's ListManagedAccounts gRPC.
         *
         *     `label` is the gateway label (e.g. "schwab", "isa-paper", "futu",
         *     "alpaca-paper") — not the broker_id.
         */
        get: operations["list_broker_account_hashes_api_admin_brokers__label__account_hashes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/brokers/{label}/reconfigure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconfigure */
        post: operations["reconfigure_api_admin_brokers__label__reconfigure_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Config */
        get: operations["list_config_api_admin_config_get"];
        put?: never;
        /** Create Config */
        post: operations["create_config_api_admin_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/config/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Config Stream */
        get: operations["config_stream_api_admin_config_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/config/{namespace}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config Entry */
        get: operations["get_config_entry_api_admin_config__namespace___key__get"];
        /** Put Config */
        put: operations["put_config_api_admin_config__namespace___key__put"];
        post?: never;
        /** Delete Config */
        delete: operations["delete_config_api_admin_config__namespace___key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/csrf/issue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue Confirmation Nonce */
        post: operations["issue_confirmation_nonce_api_admin_csrf_issue_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Instrument */
        post: operations["create_instrument_api_admin_instruments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/metrics/tier2": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push Tier2 Heartbeat */
        post: operations["push_tier2_heartbeat_api_admin_metrics_tier2_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/order-capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Order Capability */
        post: operations["set_order_capability_api_admin_order_capabilities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Secrets */
        get: operations["list_secrets_api_admin_secrets_get"];
        put?: never;
        /** Create Secret */
        post: operations["create_secret_api_admin_secrets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/secrets/{namespace}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Secret Metadata */
        get: operations["get_secret_metadata_api_admin_secrets__namespace___key__get"];
        /** Put Secret */
        put: operations["put_secret_api_admin_secrets__namespace___key__put"];
        post?: never;
        /** Delete Secret */
        delete: operations["delete_secret_api_admin_secrets__namespace___key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/secrets/{namespace}/{key}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal Secret */
        post: operations["reveal_secret_api_admin_secrets__namespace___key__reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brokers/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Broker Status */
        get: operations["list_broker_status_api_brokers_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/brokers/{broker_id}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Broker Capabilities */
        get: operations["get_broker_capabilities_api_brokers__broker_id__capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Contracts
         * @description Autocomplete proxy: forward to one healthy sidecar, cache 5 min.
         */
        get: operations["search_contracts_api_contracts_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Fills */
        get: operations["list_fills_api_fills_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/oauth/schwab/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Schwab Oauth Callback Public
         * @description Public Schwab OAuth callback. CF-Access-bypassed.
         *
         *     v0.7.4: state restored to the authorize URL. Manual-flow URLs may
         *     still omit state, in which case CSRF protection falls back to
         *     redirect_uri byte-match only.
         */
        get: operations["schwab_oauth_callback_public_api_oauth_schwab_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Orders */
        get: operations["list_orders_api_orders_get"];
        put?: never;
        /** Place Order */
        post: operations["place_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/bracket": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Place Bracket */
        post: operations["place_bracket_api_orders_bracket_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Order Events
         * @description Server-Sent Events stream for order updates.
         *
         *     Clients may send a ``Last-Event-ID`` HTTP header to replay missed events
         *     since that event id before tailing the live pubsub channel (P14).
         */
        get: operations["stream_order_events_api_orders_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/policy/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Policy */
        get: operations["get_account_policy_api_orders_policy__account_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Order */
        post: operations["preview_order_api_orders_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Order */
        get: operations["get_order_api_orders__order_id__get"];
        /** Modify Order */
        put: operations["modify_order_api_orders__order_id__put"];
        post?: never;
        /** Cancel Order */
        delete: operations["cancel_order_api_orders__order_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountAliasUpdate */
        AccountAliasUpdate: {
            /** Alias */
            alias: string;
        };
        /** AccountListResponse */
        AccountListResponse: {
            /** Accounts */
            accounts: components["schemas"]["AccountResponse"][];
            broker_maintenance: components["schemas"]["BrokerMaintenance"];
            /** Degraded Sidecars */
            degraded_sidecars: string[];
        };
        /** AccountResponse */
        AccountResponse: {
            /** Alias */
            alias: string | null;
            /**
             * Broker Id
             * @enum {string}
             */
            broker_id: "ibkr" | "futu" | "schwab" | "alpaca";
            /**
             * Currency Base
             * @default
             */
            currency_base: string;
            /** Display Order */
            display_order: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "paper";
            /** Nlv */
            nlv?: string | null;
            /** Nlv At */
            nlv_at?: string | null;
            /** Nlv Currency */
            nlv_currency?: string | null;
            /**
             * Position Count
             * @default 0
             */
            position_count: number;
        };
        /** BrokerCapabilitiesResponse */
        BrokerCapabilitiesResponse: {
            /** Broker Id */
            broker_id: string;
            /** Combos */
            combos: components["schemas"]["CapabilityComboRow"][];
            /** Order Types */
            order_types: components["schemas"]["OrderTypeRow"][];
            /** Time In Force */
            time_in_force: components["schemas"]["TimeInForceRow"][];
        };
        /**
         * BrokerMaintenance
         * @description Maintenance-window envelope. Single source of truth for both the
         *     list endpoint (broker_maintenance field on AccountListResponse) and
         *     the legacy 503 envelope used by _classify_sidecar_failure.
         */
        BrokerMaintenance: {
            /** Active */
            active: boolean;
            /** Until */
            until?: string | null;
            /** Window */
            window?: ("weekend" | "daily") | null;
        };
        /** BrokerSidecarStatus */
        BrokerSidecarStatus: {
            /**
             * Broker
             * @enum {string}
             */
            broker: "ibkr" | "futu" | "schwab" | "alpaca";
            /** Connected */
            connected: boolean;
            /** Label */
            label: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "paper";
        };
        /** BrokerSidecarStatusList */
        BrokerSidecarStatusList: {
            /** Accounts */
            accounts: components["schemas"]["BrokerSidecarStatus"][];
        };
        /** CapabilityComboRow */
        CapabilityComboRow: {
            /** Broker Id */
            broker_id: string;
            /** Notes */
            notes: string;
            /** Order Type */
            order_type: string;
            /** Supported */
            supported: boolean;
            /** Time In Force */
            time_in_force: string;
        };
        /** ConfigIn */
        ConfigIn: {
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /** Value */
            value: unknown;
            /**
             * Value Type
             * @default str
             * @enum {string}
             */
            value_type: "str" | "int" | "bool" | "json";
        };
        /** ConfigInUpsert */
        ConfigInUpsert: {
            /** Key */
            key?: string | null;
            /** Namespace */
            namespace?: string | null;
            /** Value */
            value: unknown;
            /**
             * Value Type
             * @default str
             * @enum {string}
             */
            value_type: "str" | "int" | "bool" | "json";
        };
        /** ConfigOut */
        ConfigOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Value */
            value: unknown;
            /** Value Type */
            value_type: string;
        };
        /** Contract */
        Contract: {
            /**
             * Asset Class
             * @enum {string}
             */
            asset_class: "ASSET_UNSPECIFIED" | "STOCK" | "ETF" | "OPTION" | "FUTURE" | "FOREX" | "CRYPTO" | "BOND" | "MUTUAL_FUND" | "WARRANT" | "CBBC";
            /** Conid */
            conid: string;
            /** Currency */
            currency: string;
            /** Exchange */
            exchange: string;
            /** Local Symbol */
            local_symbol: string;
            /**
             * Multiplier
             * @default
             */
            multiplier: string;
            /** Symbol */
            symbol: string;
        };
        /** ContractSummary */
        ContractSummary: {
            /** Conid */
            conid: number | string;
            /** Description */
            description: string;
        };
        /** FillListResponse */
        FillListResponse: {
            /** Fills */
            fills: components["schemas"]["FillResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** FillResponse */
        FillResponse: {
            /** Commission */
            commission?: string | null;
            /** Commission Currency */
            commission_currency?: string | null;
            /** Currency */
            currency: string;
            /** Exec Id */
            exec_id: string;
            /**
             * Executed At
             * Format: date-time
             */
            executed_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Order Id
             * Format: uuid
             */
            order_id: string;
            /** Price */
            price: string;
            /** Qty */
            qty: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Money */
        Money: {
            /** Currency */
            currency: string;
            /** Value */
            value: string;
        };
        /** Order */
        Order: {
            avg_fill_price: components["schemas"]["Money"];
            contract: components["schemas"]["Contract"];
            limit_price: components["schemas"]["Money"];
            /** Order Id */
            order_id: string;
            /**
             * Order Type
             * @enum {string}
             */
            order_type: "UNSPECIFIED" | "MARKET" | "LIMIT" | "STOP" | "STOP_LIMIT" | "TRAIL" | "TRAIL_LIMIT" | "MOC" | "MOO" | "LOC" | "LOO";
            /** Quantity */
            quantity: string;
            /** Quantity Filled */
            quantity_filled: string;
            /**
             * Side
             * @enum {string}
             */
            side: "SIDE_UNSPECIFIED" | "BUY" | "SELL";
            /**
             * Status
             * @enum {string}
             */
            status: "STATUS_UNSPECIFIED" | "PENDING" | "SUBMITTED" | "PARTIAL" | "FILLED" | "CANCELLED" | "REJECTED";
            stop_price: components["schemas"]["Money"];
            /** Submitted At */
            submitted_at: string | null;
            /**
             * Time In Force
             * @enum {string}
             */
            time_in_force: "UNSPECIFIED" | "DAY" | "GTC" | "IOC" | "FOK" | "GTD";
            /** Updated At */
            updated_at: string | null;
        };
        /** OrderBracketLeg */
        OrderBracketLeg: {
            /** Broker Order Id */
            broker_order_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Leg
             * @enum {string}
             */
            leg: "stop_loss" | "take_profit";
            /** Status */
            status: string;
        };
        /** OrderBracketParent */
        OrderBracketParent: {
            /** Broker Order Id */
            broker_order_id: string;
            /**
             * Client Order Id
             * Format: uuid
             */
            client_order_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
        };
        /** OrderBracketResponse */
        OrderBracketResponse: {
            /** Children */
            children: components["schemas"]["OrderBracketLeg"][];
            /** Oca Group */
            oca_group: string;
            parent: components["schemas"]["OrderBracketParent"];
        };
        /** OrderEvent */
        OrderEvent: {
            /** Avg Fill Price */
            avg_fill_price: string;
            /**
             * Broker Event At
             * Format: date-time
             */
            broker_event_at: string;
            /** Broker Order Id */
            broker_order_id: string;
            /** Client Order Id */
            client_order_id: string;
            /** Filled Qty */
            filled_qty: string;
            /** Raw Payload */
            raw_payload: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending_submit" | "submitted" | "partial" | "filled" | "cancelled" | "rejected" | "expired" | "inactive" | "modified";
        };
        /** OrderListResponse */
        OrderListResponse: {
            broker_maintenance: components["schemas"]["BrokerMaintenance"];
            /** Kill Switch Active */
            kill_switch_active: boolean;
            /** Orders */
            orders: components["schemas"]["OrderResponse"][];
        };
        /** OrderResponse */
        OrderResponse: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Avg Fill Price */
            avg_fill_price: string | null;
            /** Broker Order Id */
            broker_order_id: string | null;
            /** Conid */
            conid: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Events
             * @default []
             */
            events: components["schemas"]["OrderEvent"][];
            /** Filled Qty */
            filled_qty: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Last Event At */
            last_event_at: string | null;
            /** Limit Price */
            limit_price: string | null;
            /** Notional */
            notional: string;
            /**
             * Order Type
             * @enum {string}
             */
            order_type: "MARKET" | "LIMIT" | "STOP";
            /** Qty */
            qty: string;
            /**
             * Side
             * @enum {string}
             */
            side: "BUY" | "SELL";
            /**
             * Status
             * @enum {string}
             */
            status: "pending_submit" | "submitted" | "partial" | "filled" | "cancelled" | "rejected" | "expired" | "inactive" | "modified";
            /** Stop Price */
            stop_price: string | null;
            /**
             * Submission State
             * @default submitted
             * @enum {string}
             */
            submission_state: "submitted" | "pending_unknown" | "idempotent_retry";
            /** Symbol */
            symbol: string;
            /**
             * Tif
             * @enum {string}
             */
            tif: "DAY" | "GTC";
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** OrderTypeRow */
        OrderTypeRow: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Label */
            label: string;
            /** Sort Order */
            sort_order: number;
        };
        /** PolicyResponse */
        PolicyResponse: {
            /**
             * Account Id
             * Format: uuid
             */
            account_id: string;
            /** Daily Notional Cap */
            daily_notional_cap: string;
            /** Max Notional Per Order */
            max_notional_per_order: string;
            /** Notional Filled Today */
            notional_filled_today: string;
            /** Position Count */
            position_count: number;
            /** Simulator Only */
            simulator_only: boolean;
            /** Trade Enabled */
            trade_enabled: boolean;
        };
        /** Position */
        Position: {
            avg_cost: components["schemas"]["Money"];
            contract: components["schemas"]["Contract"];
            daily_pnl: components["schemas"]["Money"];
            market_price: components["schemas"]["Money"];
            market_value: components["schemas"]["Money"];
            /** Quantity */
            quantity: string;
            realized_pnl_today: components["schemas"]["Money"];
            unrealized_pnl: components["schemas"]["Money"];
        };
        /** PositionSanityResult */
        PositionSanityResult: {
            /** Current Qty */
            current_qty: string;
            /** New Qty After Fill */
            new_qty_after_fill: string;
            /** Requires Extra Attestation */
            requires_extra_attestation: boolean;
            /** Sanity Multiplier */
            sanity_multiplier: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "high" | "extreme";
        };
        /** PreviewResponse */
        PreviewResponse: {
            /**
             * Cap Status
             * @enum {string}
             */
            cap_status: "ok" | "near" | "exceeded";
            contract_summary: components["schemas"]["ContractSummary"];
            /**
             * Daily Cap Status
             * @enum {string}
             */
            daily_cap_status: "ok" | "near" | "exceeded";
            /** Daily Notional Cap */
            daily_notional_cap: string;
            /** Max Notional Per Order */
            max_notional_per_order: string;
            /** Nonce */
            nonce: string;
            /** Notional */
            notional: string;
            /** Notional Currency */
            notional_currency: string;
            /** Notional Filled Today */
            notional_filled_today: string;
            position_sanity: components["schemas"]["PositionSanityResult"];
            /** Warnings */
            warnings: string[];
        };
        /** SecretIn */
        SecretIn: {
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /** Value */
            value: unknown;
            /**
             * Value Type
             * @default str
             * @enum {string}
             */
            value_type: "str" | "int" | "bool" | "json";
        };
        /** SecretInUpsert */
        SecretInUpsert: {
            /** Key */
            key?: string | null;
            /** Namespace */
            namespace?: string | null;
            /** Value */
            value: unknown;
            /**
             * Value Type
             * @default str
             * @enum {string}
             */
            value_type: "str" | "int" | "bool" | "json";
        };
        /** SecretMetadataOut */
        SecretMetadataOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Value Type */
            value_type: string;
        };
        /** SecretRevealOut */
        SecretRevealOut: {
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /** Value */
            value: unknown;
            /** Value Type */
            value_type: string;
        };
        /** Summary */
        Summary: {
            buying_power: components["schemas"]["Money"];
            net_liquidation: components["schemas"]["Money"];
            realized_pnl: components["schemas"]["Money"];
            total_cash: components["schemas"]["Money"];
            unrealized_pnl: components["schemas"]["Money"];
            /** Updated At */
            updated_at: string | null;
        };
        /** Tier2HeartbeatIn */
        Tier2HeartbeatIn: {
            /** Last Run Seconds */
            last_run_seconds: number;
        };
        /** TimeInForceRow */
        TimeInForceRow: {
            /** Code */
            code: string;
            /** Description */
            description: string;
            /** Label */
            label: string;
            /** Requires Expiry */
            requires_expiry: boolean;
            /** Sort Order */
            sort_order: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
        };
    };
    update_account_alias_api_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountAliasUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Account uuid unknown or soft-deleted */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "account <uuid>",
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_orders_api_accounts__account_id__orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
            /** @description Account uuid unknown or soft-deleted */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "account <uuid>",
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Sidecar unreachable (Retry-After: 30) OR inside an IBKR maintenance window */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_account_positions_api_accounts__account_id__positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Position"][];
                };
            };
            /** @description Account uuid unknown or soft-deleted */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "account <uuid>",
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Sidecar unreachable (Retry-After: 30) OR inside an IBKR maintenance window */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_account_summary_api_accounts__account_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Account uuid unknown or soft-deleted */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "detail": "account <uuid>",
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Sidecar unreachable (Retry-After: 30) OR inside an IBKR maintenance window */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    disconnect_schwab_api_admin_brokers_schwab_disconnect_post: {
        parameters: {
            query?: {
                delete_credentials?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schwab_oauth_callback_admin_api_admin_brokers_schwab_oauth_callback_post: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schwab_oauth_start_api_admin_brokers_schwab_oauth_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    schwab_status_api_admin_brokers_schwab_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
        };
    };
    list_broker_account_hashes_api_admin_brokers__label__account_hashes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                label: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reconfigure_api_admin_brokers__label__reconfigure_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                label: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_config_api_admin_config_get: {
        parameters: {
            query?: {
                namespace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_config_api_admin_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    config_stream_api_admin_config_stream_get: {
        parameters: {
            query: {
                ns: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_entry_api_admin_config__namespace___key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_config_api_admin_config__namespace___key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigInUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_config_api_admin_config__namespace___key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issue_confirmation_nonce_api_admin_csrf_issue_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_instrument_api_admin_instruments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_tier2_heartbeat_api_admin_metrics_tier2_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Tier2HeartbeatIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_order_capability_api_admin_order_capabilities_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Confirm-Nonce"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_secrets_api_admin_secrets_get: {
        parameters: {
            query?: {
                namespace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretMetadataOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_secret_api_admin_secrets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretMetadataOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_secret_metadata_api_admin_secrets__namespace___key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretMetadataOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_secret_api_admin_secrets__namespace___key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretInUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretMetadataOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_secret_api_admin_secrets__namespace___key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_secret_api_admin_secrets__namespace___key__reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretRevealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_broker_status_api_brokers_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerSidecarStatusList"];
                };
            };
        };
    };
    get_broker_capabilities_api_brokers__broker_id__capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                broker_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrokerCapabilitiesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_contracts_api_contracts_search_get: {
        parameters: {
            query: {
                q: string;
                asset_class?: string;
                broker?: ("ibkr" | "futu" | "schwab") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_fills_api_fills_get: {
        parameters: {
            query: {
                account_id: string;
                from: string;
                to: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FillListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schwab_oauth_callback_public_api_oauth_schwab_callback_get: {
        parameters: {
            query: {
                code: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_orders_get: {
        parameters: {
            query?: {
                status?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    place_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
        };
    };
    place_bracket_api_orders_bracket_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderBracketResponse"];
                };
            };
        };
    };
    stream_order_events_api_orders_events_get: {
        parameters: {
            query?: {
                account_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_policy_api_orders_policy__account_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_order_api_orders_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewResponse"];
                };
            };
        };
    };
    get_order_api_orders__order_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    modify_order_api_orders__order_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_order_api_orders__order_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
