/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Accounts */
        get: operations["list_accounts_api_accounts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Account Alias */
        patch: operations["update_account_alias_api_accounts__account_id__patch"];
        trace?: never;
    };
    "/api/accounts/{account_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Orders */
        get: operations["get_account_orders_api_accounts__account_id__orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Positions */
        get: operations["get_account_positions_api_accounts__account_id__positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/{account_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Account Summary */
        get: operations["get_account_summary_api_accounts__account_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Config */
        get: operations["list_config_api_admin_config_get"];
        put?: never;
        /** Create Config */
        post: operations["create_config_api_admin_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/config/{namespace}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config Entry */
        get: operations["get_config_entry_api_admin_config__namespace___key__get"];
        /** Put Config */
        put: operations["put_config_api_admin_config__namespace___key__put"];
        post?: never;
        /** Delete Config */
        delete: operations["delete_config_api_admin_config__namespace___key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Secrets */
        get: operations["list_secrets_api_admin_secrets_get"];
        put?: never;
        /** Create Secret */
        post: operations["create_secret_api_admin_secrets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/secrets/{namespace}/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Secret Metadata */
        get: operations["get_secret_metadata_api_admin_secrets__namespace___key__get"];
        /** Put Secret */
        put: operations["put_secret_api_admin_secrets__namespace___key__put"];
        post?: never;
        /** Delete Secret */
        delete: operations["delete_secret_api_admin_secrets__namespace___key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/secrets/{namespace}/{key}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal Secret */
        post: operations["reveal_secret_api_admin_secrets__namespace___key__reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountAliasUpdate */
        AccountAliasUpdate: {
            /** Alias */
            alias: string;
        };
        /** AccountListResponse */
        AccountListResponse: {
            /** Accounts */
            accounts: components["schemas"]["AccountResponse"][];
            broker_maintenance: components["schemas"]["BrokerMaintenance"];
            /** Degraded Sidecars */
            degraded_sidecars: string[];
        };
        /** AccountResponse */
        AccountResponse: {
            /** Alias */
            alias: string | null;
            /**
             * Broker Id
             * @enum {string}
             */
            broker_id: "ibkr" | "futu" | "schwab";
            /**
             * Currency Base
             * @default
             */
            currency_base: string;
            /** Display Order */
            display_order: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Mode
             * @enum {string}
             */
            mode: "live" | "paper";
            /** Nlv */
            nlv?: string | null;
            /** Nlv At */
            nlv_at?: string | null;
            /** Nlv Currency */
            nlv_currency?: string | null;
        };
        /**
         * BrokerMaintenance
         * @description Maintenance-window envelope. Single source of truth for both the
         *     list endpoint (broker_maintenance field on AccountListResponse) and
         *     the legacy 503 envelope used by _classify_sidecar_failure.
         */
        BrokerMaintenance: {
            /** Active */
            active: boolean;
            /** Until */
            until?: string | null;
            /** Window */
            window?: ("weekend" | "daily") | null;
        };
        /** ConfigIn */
        ConfigIn: {
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /** Value */
            value: unknown;
            /**
             * Value Type
             * @default str
             * @enum {string}
             */
            value_type: "str" | "int" | "bool" | "json";
        };
        /** ConfigInUpsert */
        ConfigInUpsert: {
            /** Key */
            key?: string | null;
            /** Namespace */
            namespace?: string | null;
            /** Value */
            value: unknown;
            /**
             * Value Type
             * @default str
             * @enum {string}
             */
            value_type: "str" | "int" | "bool" | "json";
        };
        /** ConfigOut */
        ConfigOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Value */
            value: unknown;
            /** Value Type */
            value_type: string;
        };
        /** Contract */
        Contract: {
            /**
             * Asset Class
             * @enum {string}
             */
            asset_class: "ASSET_UNSPECIFIED" | "STOCK" | "ETF" | "OPTION" | "FUTURE" | "FOREX" | "CRYPTO" | "BOND" | "MUTUAL_FUND" | "WARRANT";
            /** Conid */
            conid: string;
            /** Currency */
            currency: string;
            /** Exchange */
            exchange: string;
            /** Local Symbol */
            local_symbol: string;
            /** Symbol */
            symbol: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Money */
        Money: {
            /** Currency */
            currency: string;
            /** Value */
            value: string;
        };
        /** Order */
        Order: {
            avg_fill_price: components["schemas"]["Money"];
            contract: components["schemas"]["Contract"];
            limit_price: components["schemas"]["Money"];
            /** Order Id */
            order_id: string;
            /**
             * Order Type
             * @enum {string}
             */
            order_type: "TYPE_UNSPECIFIED" | "MARKET" | "LIMIT" | "STOP" | "STOP_LIMIT";
            /** Quantity */
            quantity: string;
            /** Quantity Filled */
            quantity_filled: string;
            /**
             * Side
             * @enum {string}
             */
            side: "SIDE_UNSPECIFIED" | "BUY" | "SELL";
            /**
             * Status
             * @enum {string}
             */
            status: "STATUS_UNSPECIFIED" | "PENDING" | "SUBMITTED" | "PARTIAL" | "FILLED" | "CANCELLED" | "REJECTED";
            stop_price: components["schemas"]["Money"];
            /** Submitted At */
            submitted_at: string | null;
            /**
             * Time In Force
             * @enum {string}
             */
            time_in_force: "TIF_UNSPECIFIED" | "DAY" | "GTC" | "IOC" | "FOK";
            /** Updated At */
            updated_at: string | null;
        };
        /** Position */
        Position: {
            avg_cost: components["schemas"]["Money"];
            contract: components["schemas"]["Contract"];
            daily_pnl: components["schemas"]["Money"];
            market_price: components["schemas"]["Money"];
            market_value: components["schemas"]["Money"];
            /** Quantity */
            quantity: string;
            realized_pnl_today: components["schemas"]["Money"];
            unrealized_pnl: components["schemas"]["Money"];
        };
        /** SecretIn */
        SecretIn: {
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /** Value */
            value: unknown;
            /**
             * Value Type
             * @default str
             * @enum {string}
             */
            value_type: "str" | "int" | "bool" | "json";
        };
        /** SecretInUpsert */
        SecretInUpsert: {
            /** Key */
            key?: string | null;
            /** Namespace */
            namespace?: string | null;
            /** Value */
            value: unknown;
            /**
             * Value Type
             * @default str
             * @enum {string}
             */
            value_type: "str" | "int" | "bool" | "json";
        };
        /** SecretMetadataOut */
        SecretMetadataOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Value Type */
            value_type: string;
        };
        /** SecretRevealOut */
        SecretRevealOut: {
            /** Key */
            key: string;
            /** Namespace */
            namespace: string;
            /** Value */
            value: unknown;
            /** Value Type */
            value_type: string;
        };
        /** Summary */
        Summary: {
            buying_power: components["schemas"]["Money"];
            net_liquidation: components["schemas"]["Money"];
            realized_pnl: components["schemas"]["Money"];
            total_cash: components["schemas"]["Money"];
            unrealized_pnl: components["schemas"]["Money"];
            /** Updated At */
            updated_at: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_accounts_api_accounts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["AccountListResponse"];
                };
            };
        };
    };
    update_account_alias_api_accounts__account_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountAliasUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["AccountResponse"];
                };
            };
            /** @description Account uuid unknown or soft-deleted */
            404: {
                headers: Record<string, unknown>;
                content: {
                    /**
                     * @example {
                     *       "detail": "account <uuid>",
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_account_orders_api_accounts__account_id__orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
            /** @description Account uuid unknown or soft-deleted */
            404: {
                headers: Record<string, unknown>;
                content: {
                    /**
                     * @example {
                     *       "detail": "account <uuid>",
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Sidecar unreachable (Retry-After: 30) OR inside an IBKR maintenance window */
            503: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_account_positions_api_accounts__account_id__positions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["Position"][];
                };
            };
            /** @description Account uuid unknown or soft-deleted */
            404: {
                headers: Record<string, unknown>;
                content: {
                    /**
                     * @example {
                     *       "detail": "account <uuid>",
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Sidecar unreachable (Retry-After: 30) OR inside an IBKR maintenance window */
            503: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_account_summary_api_accounts__account_id__summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["Summary"];
                };
            };
            /** @description Account uuid unknown or soft-deleted */
            404: {
                headers: Record<string, unknown>;
                content: {
                    /**
                     * @example {
                     *       "detail": "account <uuid>",
                     *       "error": "not_found"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Sidecar unreachable (Retry-After: 30) OR inside an IBKR maintenance window */
            503: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_config_api_admin_config_get: {
        parameters: {
            query?: {
                namespace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ConfigOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_config_api_admin_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_entry_api_admin_config__namespace___key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_config_api_admin_config__namespace___key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigInUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_config_api_admin_config__namespace___key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: Record<string, unknown>;
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_secrets_api_admin_secrets_get: {
        parameters: {
            query?: {
                namespace?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["SecretMetadataOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_secret_api_admin_secrets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["SecretMetadataOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_secret_metadata_api_admin_secrets__namespace___key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["SecretMetadataOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_secret_api_admin_secrets__namespace___key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecretInUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["SecretMetadataOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_secret_api_admin_secrets__namespace___key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: Record<string, unknown>;
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_secret_api_admin_secrets__namespace___key__reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                namespace: string;
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["SecretRevealOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": Record<string, string>;
                };
            };
        };
    };
    get_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: Record<string, unknown>;
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
