# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from sidecar_alpaca._generated.broker.v1 import broker_pb2 as broker_dot_v1_dot_broker__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in broker/v1/broker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrokerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/broker.v1.Broker/Health',
                request_serializer=broker_dot_v1_dot_broker__pb2.HealthRequest.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListManagedAccounts = channel.unary_unary(
                '/broker.v1.Broker/ListManagedAccounts',
                request_serializer=broker_dot_v1_dot_broker__pb2.Empty.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.AccountsResponse.FromString,
                _registered_method=True)
        self.GetAccountSummary = channel.unary_unary(
                '/broker.v1.Broker/GetAccountSummary',
                request_serializer=broker_dot_v1_dot_broker__pb2.AccountRef.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.SummaryResponse.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/broker.v1.Broker/GetPositions',
                request_serializer=broker_dot_v1_dot_broker__pb2.AccountRef.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.PositionsResponse.FromString,
                _registered_method=True)
        self.GetOrders = channel.unary_unary(
                '/broker.v1.Broker/GetOrders',
                request_serializer=broker_dot_v1_dot_broker__pb2.AccountRef.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.OrdersResponse.FromString,
                _registered_method=True)
        self.GetContract = channel.unary_unary(
                '/broker.v1.Broker/GetContract',
                request_serializer=broker_dot_v1_dot_broker__pb2.ContractRef.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.ContractResponse.FromString,
                _registered_method=True)
        self.PlaceOrder = channel.unary_unary(
                '/broker.v1.Broker/PlaceOrder',
                request_serializer=broker_dot_v1_dot_broker__pb2.PlaceOrderRequest.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.PlaceOrderResponse.FromString,
                _registered_method=True)
        self.CancelOrder = channel.unary_unary(
                '/broker.v1.Broker/CancelOrder',
                request_serializer=broker_dot_v1_dot_broker__pb2.CancelOrderRequest.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.CancelOrderResponse.FromString,
                _registered_method=True)
        self.OrderEvent = channel.unary_stream(
                '/broker.v1.Broker/OrderEvent',
                request_serializer=broker_dot_v1_dot_broker__pb2.AccountRef.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.OrderEventMessage.FromString,
                _registered_method=True)
        self.SearchContracts = channel.unary_unary(
                '/broker.v1.Broker/SearchContracts',
                request_serializer=broker_dot_v1_dot_broker__pb2.SearchContractsRequest.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.SearchContractsResponse.FromString,
                _registered_method=True)
        self.ModifyOrder = channel.unary_unary(
                '/broker.v1.Broker/ModifyOrder',
                request_serializer=broker_dot_v1_dot_broker__pb2.ModifyOrderRequest.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.ModifyOrderResponse.FromString,
                _registered_method=True)
        self.PlaceBracket = channel.unary_unary(
                '/broker.v1.Broker/PlaceBracket',
                request_serializer=broker_dot_v1_dot_broker__pb2.PlaceBracketRequest.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.PlaceBracketResponse.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/broker.v1.Broker/Configure',
                request_serializer=broker_dot_v1_dot_broker__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.ConfigureResponse.FromString,
                _registered_method=True)
        self.StreamQuotes = channel.stream_stream(
                '/broker.v1.Broker/StreamQuotes',
                request_serializer=broker_dot_v1_dot_broker__pb2.StreamQuotesRequest.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.QuoteMessage.FromString,
                _registered_method=True)
        self.GetHistoricalBars = channel.unary_unary(
                '/broker.v1.Broker/GetHistoricalBars',
                request_serializer=broker_dot_v1_dot_broker__pb2.GetHistoricalBarsRequest.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.GetHistoricalBarsResponse.FromString,
                _registered_method=True)
        self.PreviewOrder = channel.unary_unary(
                '/broker.v1.Broker/PreviewOrder',
                request_serializer=broker_dot_v1_dot_broker__pb2.PreviewOrderRequest.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.PreviewOrderResponse.FromString,
                _registered_method=True)


class BrokerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListManagedAccounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OrderEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchContracts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PlaceBracket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Phase 6: backend ships per-sidecar credentials (futu unlock + RSA priv)
        at registry boot. IBKR sidecars implement as no-op-returning-ok.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamQuotes(self, request_iterator, context):
        """Phase 7b.1 — bidirectional streaming quotes. Backend dials sidecar
        (sidecar = gRPC server, matches Health/GetPositions). Subscribe/Unsubscribe/
        Resync/Heartbeat travel client→server; QuoteMessage travels server→client.
        See spec docs/superpowers/specs/2026-05-04-phase7b1-streaming-quotes-design.md §4.2.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalBars(self, request, context):
        """Phase 9 — historical OHLCV backfill. BarService calls this for cache misses
        and pre-warm; sidecar chunks/paces internally per broker SDK quotas.
        See docs/superpowers/specs/2026-05-07-phase9-charting-design.md §4 lines 622-645.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewOrder(self, request, context):
        """Phase 10a — pre-trade margin/risk preview RPC. IBKR uses ib_async
        placeOrder(whatIf=True) + filledEvent.wait; Schwab uses POST
        /trader/v1/accounts/{accountHash}/previewOrder; Alpaca returns
        UNIMPLEMENTED. Money fields are Decimal-strings per [C2].
        Spec: docs/superpowers/specs/2026-05-08-phase10a-risk-engine-design.md §5.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrokerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.HealthRequest.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.HealthResponse.SerializeToString,
            ),
            'ListManagedAccounts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListManagedAccounts,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.Empty.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.AccountsResponse.SerializeToString,
            ),
            'GetAccountSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountSummary,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.AccountRef.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.SummaryResponse.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.AccountRef.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.PositionsResponse.SerializeToString,
            ),
            'GetOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrders,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.AccountRef.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.OrdersResponse.SerializeToString,
            ),
            'GetContract': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContract,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.ContractRef.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.ContractResponse.SerializeToString,
            ),
            'PlaceOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceOrder,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.PlaceOrderRequest.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.PlaceOrderResponse.SerializeToString,
            ),
            'CancelOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelOrder,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.CancelOrderRequest.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.CancelOrderResponse.SerializeToString,
            ),
            'OrderEvent': grpc.unary_stream_rpc_method_handler(
                    servicer.OrderEvent,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.AccountRef.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.OrderEventMessage.SerializeToString,
            ),
            'SearchContracts': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchContracts,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.SearchContractsRequest.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.SearchContractsResponse.SerializeToString,
            ),
            'ModifyOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyOrder,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.ModifyOrderRequest.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.ModifyOrderResponse.SerializeToString,
            ),
            'PlaceBracket': grpc.unary_unary_rpc_method_handler(
                    servicer.PlaceBracket,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.PlaceBracketRequest.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.PlaceBracketResponse.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.ConfigureRequest.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.ConfigureResponse.SerializeToString,
            ),
            'StreamQuotes': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamQuotes,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.StreamQuotesRequest.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.QuoteMessage.SerializeToString,
            ),
            'GetHistoricalBars': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoricalBars,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.GetHistoricalBarsRequest.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.GetHistoricalBarsResponse.SerializeToString,
            ),
            'PreviewOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewOrder,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.PreviewOrderRequest.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.PreviewOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'broker.v1.Broker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('broker.v1.Broker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Broker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/Health',
            broker_dot_v1_dot_broker__pb2.HealthRequest.SerializeToString,
            broker_dot_v1_dot_broker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListManagedAccounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/ListManagedAccounts',
            broker_dot_v1_dot_broker__pb2.Empty.SerializeToString,
            broker_dot_v1_dot_broker__pb2.AccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetAccountSummary',
            broker_dot_v1_dot_broker__pb2.AccountRef.SerializeToString,
            broker_dot_v1_dot_broker__pb2.SummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetPositions',
            broker_dot_v1_dot_broker__pb2.AccountRef.SerializeToString,
            broker_dot_v1_dot_broker__pb2.PositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetOrders',
            broker_dot_v1_dot_broker__pb2.AccountRef.SerializeToString,
            broker_dot_v1_dot_broker__pb2.OrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetContract',
            broker_dot_v1_dot_broker__pb2.ContractRef.SerializeToString,
            broker_dot_v1_dot_broker__pb2.ContractResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/PlaceOrder',
            broker_dot_v1_dot_broker__pb2.PlaceOrderRequest.SerializeToString,
            broker_dot_v1_dot_broker__pb2.PlaceOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/CancelOrder',
            broker_dot_v1_dot_broker__pb2.CancelOrderRequest.SerializeToString,
            broker_dot_v1_dot_broker__pb2.CancelOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OrderEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/broker.v1.Broker/OrderEvent',
            broker_dot_v1_dot_broker__pb2.AccountRef.SerializeToString,
            broker_dot_v1_dot_broker__pb2.OrderEventMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchContracts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/SearchContracts',
            broker_dot_v1_dot_broker__pb2.SearchContractsRequest.SerializeToString,
            broker_dot_v1_dot_broker__pb2.SearchContractsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/ModifyOrder',
            broker_dot_v1_dot_broker__pb2.ModifyOrderRequest.SerializeToString,
            broker_dot_v1_dot_broker__pb2.ModifyOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PlaceBracket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/PlaceBracket',
            broker_dot_v1_dot_broker__pb2.PlaceBracketRequest.SerializeToString,
            broker_dot_v1_dot_broker__pb2.PlaceBracketResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/Configure',
            broker_dot_v1_dot_broker__pb2.ConfigureRequest.SerializeToString,
            broker_dot_v1_dot_broker__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamQuotes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/broker.v1.Broker/StreamQuotes',
            broker_dot_v1_dot_broker__pb2.StreamQuotesRequest.SerializeToString,
            broker_dot_v1_dot_broker__pb2.QuoteMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistoricalBars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/GetHistoricalBars',
            broker_dot_v1_dot_broker__pb2.GetHistoricalBarsRequest.SerializeToString,
            broker_dot_v1_dot_broker__pb2.GetHistoricalBarsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.Broker/PreviewOrder',
            broker_dot_v1_dot_broker__pb2.PreviewOrderRequest.SerializeToString,
            broker_dot_v1_dot_broker__pb2.PreviewOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BackendCallbackStub(object):
    """Phase 7a — sidecar→backend single-writer token-refresh callback (architect C2).
    This service is implemented by the BACKEND (not by sidecars). Sidecars are
    gRPC clients of this service when they need a fresh token pair. Backend
    holds the PG advisory lock during the actual refresh; sidecars never call
    Schwab's /oauth/token endpoint directly.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestTokenRefresh = channel.unary_unary(
                '/broker.v1.BackendCallback/RequestTokenRefresh',
                request_serializer=broker_dot_v1_dot_broker__pb2.TokenRefreshRequest.SerializeToString,
                response_deserializer=broker_dot_v1_dot_broker__pb2.TokenRefreshResponse.FromString,
                _registered_method=True)


class BackendCallbackServicer(object):
    """Phase 7a — sidecar→backend single-writer token-refresh callback (architect C2).
    This service is implemented by the BACKEND (not by sidecars). Sidecars are
    gRPC clients of this service when they need a fresh token pair. Backend
    holds the PG advisory lock during the actual refresh; sidecars never call
    Schwab's /oauth/token endpoint directly.
    """

    def RequestTokenRefresh(self, request, context):
        """broker_id selects which broker's tokens to refresh. Only "schwab"
        currently uses this path; other brokers reuse their existing auth.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BackendCallbackServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestTokenRefresh': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestTokenRefresh,
                    request_deserializer=broker_dot_v1_dot_broker__pb2.TokenRefreshRequest.FromString,
                    response_serializer=broker_dot_v1_dot_broker__pb2.TokenRefreshResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'broker.v1.BackendCallback', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('broker.v1.BackendCallback', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BackendCallback(object):
    """Phase 7a — sidecar→backend single-writer token-refresh callback (architect C2).
    This service is implemented by the BACKEND (not by sidecars). Sidecars are
    gRPC clients of this service when they need a fresh token pair. Backend
    holds the PG advisory lock during the actual refresh; sidecars never call
    Schwab's /oauth/token endpoint directly.
    """

    @staticmethod
    def RequestTokenRefresh(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/broker.v1.BackendCallback/RequestTokenRefresh',
            broker_dot_v1_dot_broker__pb2.TokenRefreshRequest.SerializeToString,
            broker_dot_v1_dot_broker__pb2.TokenRefreshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
