"""add bot engine tables (bots, bot_accounts, bot_risk_caps, bot_runs hypertable, bot_orders); widen attempt_kind

Revision ID: 0061
Revises: 0060
Create Date: 2026-05-19
"""

from alembic import op
import sqlalchemy as sa

revision = "0061"
down_revision = "0060"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bots",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("strategy_file", sa.TEXT(), nullable=False),
        sa.Column("params_json", sa.JSON(), server_default=sa.text("'{}'::json"), nullable=False),
        sa.Column("params_schema_json", sa.JSON(), nullable=True),
        sa.Column("version", sa.INTEGER(), server_default=sa.text("1"), nullable=False),
        sa.Column("status", sa.TEXT(), server_default=sa.text("'stopped'::text"), nullable=False),
        sa.Column("error_msg", sa.TEXT(), nullable=True),
        sa.Column("mode", sa.TEXT(), server_default=sa.text("'paper'::text"), nullable=False),
        sa.Column("bar_timeframe", sa.TEXT(), server_default=sa.text("'1m'::text"), nullable=False),
        sa.Column("deleted_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.CheckConstraint(
            "status IN ('stopped', 'starting', 'running', 'pausing', 'paused', 'error')",
            name="bots_status_check",
        ),
        sa.CheckConstraint(
            "mode IN ('paper', 'live')",
            name="bots_mode_check",
        ),
        sa.CheckConstraint(
            "LENGTH(error_msg) <= 2000",
            name="bots_error_msg_len_check",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index(
        "ix_bots_status",
        "bots",
        ["status"],
        postgresql_where=sa.text("deleted_at IS NULL"),
    )

    op.create_table(
        "bot_accounts",
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["account_id"], ["broker_accounts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("bot_id", "account_id"),
    )

    op.create_index(
        "ix_bot_accounts_account_id",
        "bot_accounts",
        ["account_id"],
    )

    op.create_table(
        "bot_risk_caps",
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("max_position_size", sa.Numeric(20, 8), nullable=True),
        sa.Column("max_daily_loss", sa.Numeric(20, 8), nullable=True),
        sa.Column("max_open_orders", sa.INTEGER(), nullable=True),
        sa.Column("max_order_size", sa.Numeric(20, 8), nullable=True),
        sa.Column("allowed_asset_classes", sa.ARRAY(sa.TEXT()), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("bot_id"),
    )

    op.create_table(
        "bot_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.INTEGER(), nullable=False),
        sa.Column("started_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("stopped_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("stop_reason", sa.TEXT(), nullable=True),
        sa.CheckConstraint(
            "stop_reason IN ('manual', 'error', 'daily_loss_cap', 'kill_switch')",
            name="bot_runs_stop_reason_check",
        ),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", "started_at"),
    )

    op.execute("SELECT create_hypertable('bot_runs', 'started_at', chunk_time_interval => INTERVAL '7 days')")
    op.execute("SELECT add_retention_policy('bot_runs', INTERVAL '90 days')")

    op.create_index(
        "ix_bot_runs_bot_id_started_at",
        "bot_runs",
        ["bot_id", sa.text("started_at DESC")],
    )

    op.create_table(
        "bot_orders",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("bot_id", sa.UUID(), nullable=False),
        sa.Column("placed_at", sa.TIMESTAMP(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("order_id"),
    )

    op.create_index(
        "ix_bot_orders_bot_id_placed_at",
        "bot_orders",
        ["bot_id", sa.text("placed_at DESC")],
    )

    op.execute("ALTER TABLE risk_decisions DROP CONSTRAINT IF EXISTS risk_decisions_attempt_kind_check")
    op.execute("""ALTER TABLE risk_decisions ADD CONSTRAINT risk_decisions_attempt_kind_check CHECK (attempt_kind IN ('preview','place','modify','place_order','modify_order','combo_preview','combo_place','combo_autoclose','telegram','telegram_confirm','earnings_hook_flat','bot_place_order'))""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE risk_decisions DROP CONSTRAINT IF EXISTS risk_decisions_attempt_kind_check")
    op.execute("""ALTER TABLE risk_decisions ADD CONSTRAINT risk_decisions_attempt_kind_check CHECK (attempt_kind IN ('preview','place','modify','place_order','modify_order','combo_preview','combo_place','combo_autoclose','telegram','telegram_confirm','earnings_hook_flat'))""")

    op.drop_index("ix_bot_orders_bot_id_placed_at", table_name="bot_orders")
    op.drop_table("bot_orders")

    op.drop_index("ix_bot_runs_bot_id_started_at", table_name="bot_runs")
    op.drop_table("bot_runs")

    op.drop_table("bot_risk_caps")

    op.drop_index("ix_bot_accounts_account_id", table_name="bot_accounts")
    op.drop_table("bot_accounts")

    op.drop_index("ix_bots_status", table_name="bots")
    op.drop_table("bots")
    # ### end Alembic commands ###
