#!/usr/bin/env bash
# sidecar_futu/scripts/proto-gen.sh
# Regenerate Python gRPC stubs for the futu sidecar from proto/broker/v1/broker.proto.
#
# Mirrors sidecar/scripts/proto-gen.sh: prefer `buf` if available, otherwise
# fall back to grpc_tools.protoc with an import rewrite so the generated
# package resolves under `sidecar_futu._generated.broker.v1`.

set -euo pipefail
cd "$(dirname "$0")/.."           # sidecar_futu/

mkdir -p _generated/broker/v1
: > _generated/__init__.py
: > _generated/broker/__init__.py
: > _generated/broker/v1/__init__.py

if command -v buf >/dev/null 2>&1; then
  ( cd ../proto && buf generate )
  # buf.gen.yaml writes to backend/app/_generated and sidecar/_generated; we
  # additionally want sidecar_futu/_generated to receive identical stubs.
  # Copy from sidecar/_generated (regenerated by the same buf invocation)
  # and rewrite the package import path.
  cp -r ../sidecar/_generated/broker/v1/. _generated/broker/v1/
  # buf raw output is `from v1 import broker_pb2 as ...` (not yet rewritten).
  # Match both that form and any pre-rewritten sidecar form.
  sed -i \
    -e 's|^from v1 import broker_pb2|from sidecar_futu._generated.broker.v1 import broker_pb2|' \
    -e 's|^from sidecar\._generated\.broker\.v1 import broker_pb2|from sidecar_futu._generated.broker.v1 import broker_pb2|' \
    _generated/broker/v1/broker_pb2_grpc.py
  echo "[ok] proto codegen copied from sidecar/_generated -> sidecar_futu/_generated/"
  exit 0
fi

echo "[warn] buf not installed; falling back to grpc_tools.protoc"
uv run python -m grpc_tools.protoc \
  --proto_path=../proto \
  --python_out=_generated \
  --grpc_python_out=_generated \
  --pyi_out=_generated \
  broker/v1/broker.proto

# grpc_tools emits `from broker.v1 import broker_pb2`; rewrite to the
# fully-qualified package path under sidecar_futu._generated.
sed -i 's|^from broker\.v1 import broker_pb2|from sidecar_futu._generated.broker.v1 import broker_pb2|' \
  _generated/broker/v1/broker_pb2_grpc.py

echo "[ok] sidecar_futu proto codegen complete via grpc_tools -> sidecar_futu/_generated/"
